version: "3.5"
services:
  # Redis
  redis:
    restart: always
    image: redis:5-alpine  # you can browse all images at https://hub.docker.com/
    ports:
      - 6379:6379
  # Generic PostgreSQL database
  postgres:
    restart: always
    image: postgres:12
    ports:
      # Different port in case host has Postgres installed already
      - 5434:5432
    environment:
      - POSTGRES_USER=cscc09
      - POSTGRES_PASSWORD=cscc09
    # For any persistent storage, you would need to mount a volume to the docker container
    # so that your data stays intact.
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./postgres12/:/docker-entrypoint-initdb.d/
  mongo:
    restart: always
    image: mongo:4.2.7-bionic
    ports:
      # Different port in case host has MongoDB installed already
      - 27018:27017
    # For any persistent storage, you would need to mount a volume to the docker container
    # so that your data stays intact.
    volumes:
      - mongo-volume:/data/db/
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: cscc09
      MONGO_INITDB_ROOT_PASSWORD: cscc09
      MONGO_INITDB_DATABASE: admin
  kafka:
    restart: always
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      - ADVERTISED_HOST=localhost
      - ADVERTISED_PORT=9092
volumes:
  postgres-volume:
  mongo-volume: